/** Nasdaq-100 + cash/index aliases. Tickers stay as typed; this is display-only. */

const NAMES = {
  CASH: { en: 'Cash', zh: '现金' },
  QQQ: { en: 'Invesco QQQ', zh: '纳指 ETF' },
  SPY: { en: 'SPDR S&P 500', zh: '标普 ETF' },
  AAPL: { en: 'Apple', zh: '苹果' },
  ABNB: { en: 'Airbnb', zh: '爱彼迎' },
  ADBE: { en: 'Adobe', zh: '奥多比' },
  ADI: { en: 'Analog Devices', zh: '亚德诺' },
  ADP: { en: 'ADP', zh: '自动数据处理' },
  ADSK: { en: 'Autodesk', zh: '欧特克' },
  AEP: { en: 'American Electric Power', zh: '美国电力' },
  AMAT: { en: 'Applied Materials', zh: '应用材料' },
  AMD: { en: 'AMD', zh: '超威' },
  AMGN: { en: 'Amgen', zh: '安进' },
  AMZN: { en: 'Amazon', zh: '亚马逊' },
  APP: { en: 'AppLovin', zh: 'AppLovin' },
  ARM: { en: 'Arm', zh: 'ARM' },
  ASML: { en: 'ASML', zh: '阿斯麦' },
  AVGO: { en: 'Broadcom', zh: '博通' },
  AXON: { en: 'Axon', zh: 'Axon' },
  AZN: { en: 'AstraZeneca', zh: '阿斯利康' },
  BIIB: { en: 'Biogen', zh: '百健' },
  BKNG: { en: 'Booking', zh: '缤客' },
  BKR: { en: 'Baker Hughes', zh: '贝克休斯' },
  CCEP: { en: 'Coca-Cola Europacific', zh: '可口可乐欧洲' },
  CDNS: { en: 'Cadence', zh: '铿腾' },
  CDW: { en: 'CDW', zh: 'CDW' },
  CEG: { en: 'Constellation Energy', zh: '星座能源' },
  CHTR: { en: 'Charter', zh: '特许通信' },
  CMCSA: { en: 'Comcast', zh: '康卡斯特' },
  COST: { en: 'Costco', zh: '开市客' },
  CPRT: { en: 'Copart', zh: '科帕' },
  CRWD: { en: 'CrowdStrike', zh: '众击' },
  CSCO: { en: 'Cisco', zh: '思科' },
  CSGP: { en: 'CoStar', zh: '科斯塔' },
  CSX: { en: 'CSX', zh: 'CSX' },
  CTAS: { en: 'Cintas', zh: '辛塔斯' },
  CTSH: { en: 'Cognizant', zh: '高知特' },
  DASH: { en: 'DoorDash', zh: 'DoorDash' },
  DDOG: { en: 'Datadog', zh: 'Datadog' },
  DXCM: { en: 'Dexcom', zh: '德康' },
  EA: { en: 'Electronic Arts', zh: '艺电' },
  EXC: { en: 'Exelon', zh: '爱克斯龙' },
  FANG: { en: 'Diamondback', zh: '响尾蛇能源' },
  FAST: { en: 'Fastenal', zh: '快扣' },
  FTNT: { en: 'Fortinet', zh: '飞塔' },
  GEHC: { en: 'GE HealthCare', zh: '通用医疗' },
  GFS: { en: 'GlobalFoundries', zh: '格芯' },
  GILD: { en: 'Gilead', zh: '吉利德' },
  GOOG: { en: 'Alphabet', zh: '谷歌' },
  GOOGL: { en: 'Alphabet', zh: '谷歌' },
  HON: { en: 'Honeywell', zh: '霍尼韦尔' },
  IDXX: { en: 'IDEXX', zh: '爱德士' },
  INTC: { en: 'Intel', zh: '英特尔' },
  INTU: { en: 'Intuit', zh: '财捷' },
  ISRG: { en: 'Intuitive Surgical', zh: '直觉外科' },
  KDP: { en: 'Keurig Dr Pepper', zh: '可口可乐胡椒' },
  KHC: { en: 'Kraft Heinz', zh: '卡夫亨氏' },
  KLAC: { en: 'KLA', zh: '科磊' },
  LIN: { en: 'Linde', zh: '林德' },
  LRCX: { en: 'Lam Research', zh: '泛林' },
  MAR: { en: 'Marriott', zh: '万豪' },
  MCHP: { en: 'Microchip', zh: '微芯' },
  MDLZ: { en: 'Mondelez', zh: '亿滋' },
  MELI: { en: 'MercadoLibre', zh: '美客多' },
  META: { en: 'Meta', zh: 'Meta' },
  MNST: { en: 'Monster', zh: '魔爪' },
  MRNA: { en: 'Moderna', zh: '莫德纳' },
  MRVL: { en: 'Marvell', zh: '迈威尔' },
  MSFT: { en: 'Microsoft', zh: '微软' },
  MSTR: { en: 'MicroStrategy', zh: '微策略' },
  MU: { en: 'Micron', zh: '美光' },
  NFLX: { en: 'Netflix', zh: '奈飞' },
  NVDA: { en: 'NVIDIA', zh: '英伟达' },
  NXPI: { en: 'NXP', zh: '恩智浦' },
  ODFL: { en: 'Old Dominion', zh: '旧自治领' },
  ON: { en: 'ON Semiconductor', zh: '安森美' },
  ORLY: { en: "O'Reilly", zh: '奥莱利' },
  PANW: { en: 'Palo Alto', zh: '帕洛阿尔托' },
  PAYX: { en: 'Paychex', zh: '沛齐' },
  PCAR: { en: 'PACCAR', zh: '帕卡' },
  PDD: { en: 'PDD Holdings', zh: '拼多多' },
  PEP: { en: 'PepsiCo', zh: '百事' },
  PLTR: { en: 'Palantir', zh: '帕兰蒂尔' },
  PYPL: { en: 'PayPal', zh: '贝宝' },
  QCOM: { en: 'Qualcomm', zh: '高通' },
  REGN: { en: 'Regeneron', zh: '再生元' },
  ROP: { en: 'Roper', zh: '罗珀' },
  ROST: { en: 'Ross Stores', zh: '罗斯百货' },
  SBUX: { en: 'Starbucks', zh: '星巴克' },
  SHOP: { en: 'Shopify', zh: 'Shopify' },
  SNPS: { en: 'Synopsys', zh: '新思' },
  TEAM: { en: 'Atlassian', zh: 'Atlassian' },
  TMUS: { en: 'T-Mobile', zh: 'T-Mobile' },
  TRI: { en: 'Thomson Reuters', zh: '汤森路透' },
  TSLA: { en: 'Tesla', zh: '特斯拉' },
  TTD: { en: 'The Trade Desk', zh: 'The Trade Desk' },
  TTWO: { en: 'Take-Two', zh: 'Take-Two' },
  TXN: { en: 'Texas Instruments', zh: '德州仪器' },
  VRSK: { en: 'Verisk', zh: '维里斯克' },
  VRTX: { en: 'Vertex', zh: '福泰' },
  WBD: { en: 'Warner Bros Discovery', zh: '华纳兄弟探索' },
  WDAY: { en: 'Workday', zh: 'Workday' },
  XEL: { en: 'Xcel Energy', zh: '埃克西尔' },
  ZS: { en: 'Zscaler', zh: 'Zscaler' },
};

export function displayName(symbol, lang, remoteZh = {}) {
  const ticker = String(symbol || '')
    .trim()
    .toUpperCase();
  if (!ticker) return '';
  if (lang === 'zh') {
    const custom = String(remoteZh[ticker] || '').trim();
    if (custom) return custom;
    return NAMES[ticker]?.zh || '';
  }
  const row = NAMES[ticker];
  if (!row) return '';
  return row.en;
}

export function chineseName(symbol, remoteZh = {}) {
  return displayName(symbol, 'zh', remoteZh);
}
